const app=document.getElementById('app');let currentView='dashboard',selected=null,timer=null,seconds=0;
const state={done:JSON.parse(localStorage.getItem('tcfDone')||'[]'),mistakes:JSON.parse(localStorage.getItem('tcfMistakes')||'[]')};
function save(){localStorage.setItem('tcfDone',JSON.stringify(state.done));localStorage.setItem('tcfMistakes',JSON.stringify(state.mistakes));}
function nav(){document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',b.dataset.view===currentView));}
function esc(s){return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')}
function card(q){return `<article class="card question-card" onclick="openQuestion('${q.id}')"><div><span class="badge task">Tâche ${q.task}</span><span class="badge purple">${esc(q.motherTopic)}</span>${q.hot>=5?'<span class="badge hot">🔥 高频</span>':''}</div><h3>${esc(q.question)}</h3><p class="cn">${esc(q.cn)}</p><div class="meta"><span>${q.month}</span><span>出现 ${q.appearances.length} 次</span></div></article>`}
function dashboard(){let t2=QUESTIONS.filter(q=>q.task===2),t3=QUESTIONS.filter(q=>q.task===3);app.innerHTML=`<section class="hero"><div><p class="eyebrow">TCF QUÉBEC · EXPRESSION ORALE</p><h1>不是背几百道题，<br>而是掌握 <em>母题 + 句型 + 范文</em></h1><p>每道题都配完整范文；每个主题再拆成通用句、半通用句和回答框架。</p></div><div class="hero-actions"><button class="primary" onclick="route('task3')">开始 Tâche 3</button><button onclick="route('task2')">练 Tâche 2</button></div></section><section class="stats"><div><small>Tâche 2</small><b>${t2.length}</b><span>互动题</span></div><div><small>Tâche 3</small><b>${t3.length}</b><span>观点题</span></div><div><small>母题</small><b>${MOTHER_TOPICS.length}</b><span>主题归类</span></div><div><small>已完成</small><b>${state.done.length}</b><span>本机记录</span></div></section><section class="section"><div class="legend"><div class="legend-item purple-bg"><b>🟣 题型 / 母题</b><span>告诉你“这道题属于哪一种题”。</span></div><div class="legend-item green-bg"><b>🟢 通用句 + 范文</b><span>直接学习、朗读和背诵，不需要自己填写。</span></div><div class="legend-item teal-bg"><b>🔵 半通用句</b><span>根据具体主题稍微替换名词即可使用。</span></div></div></section><section class="section"><div class="section-head"><h2>🔥 高频母题</h2><button onclick="route('topics')">查看全部</button></div><div class="grid">${MOTHER_TOPICS.slice(0,6).map(topicCard).join('')}</div></section><section class="section"><div class="section-head"><h2>近期高频题</h2></div><div class="grid">${QUESTIONS.filter(q=>q.hot>=5).slice(0,6).map(card).join('')}</div></section>`;nav()}
function topicCard(topic){let arr=QUESTIONS.filter(q=>q.motherTopic===topic);return `<article class="card topic-card" onclick="openTopic('${encodeURIComponent(topic)}')"><span class="badge purple">🟣 母题</span><h3>${esc(topic)}</h3><p>${arr.length} 道题 · Tâche 2 ${arr.filter(x=>x.task===2).length} · Tâche 3 ${arr.filter(x=>x.task===3).length}</p><div class="mini">${arr.filter(x=>x.hot>=5).length} 道高频</div></article>`}
function showList(task){currentView=task===2?'task2':'task3';let arr=QUESTIONS.filter(q=>q.task===task);app.innerHTML=`<section class="hero compact"><div><p class="eyebrow">${task===2?'INTERACTION':'POINT DE VUE'}</p><h1>Tâche ${task}</h1><p>${task===2?'重点：学会自然、完整地连续提问。':'重点：学会 4 分 30 秒的结构化表达。'} 每道题都有完整范文。</p></div><button class="primary" onclick="randomQuestion(${task})">🎲 随机一题</button></section><section class="filters"><select id="topic"><option value="">全部母题</option>${[...new Set(arr.map(q=>q.motherTopic))].map(x=>`<option>${esc(x)}</option>`).join('')}</select><select id="month"><option value="">全部月份</option>${[...new Set(arr.map(q=>q.month))].sort().reverse().map(x=>`<option>${x}</option>`).join('')}</select><select id="hot"><option value="">全部频率</option><option value="5">🔥 高频</option><option value="4">高频以上</option></select><input id="search" placeholder="搜索题目…"></section><div id="list" class="grid"></div>`;['topic','month','hot','search'].forEach(id=>document.getElementById(id).addEventListener('input',renderList));renderList();nav()}
function renderList(){let task=currentView==='task2'?2:3,topic=document.getElementById('topic').value,month=document.getElementById('month').value,hot=document.getElementById('hot').value,s=document.getElementById('search').value.toLowerCase();let arr=QUESTIONS.filter(q=>q.task===task&&(!topic||q.motherTopic===topic)&&(!month||q.month===month)&&(!hot||q.hot>=+hot)&&(!s||(q.question+q.cn+q.motherTopic).toLowerCase().includes(s)));document.getElementById('list').innerHTML=arr.length?arr.map(card).join(''):'<div class="empty">没有符合条件的题目。</div>'}
function openTopic(encoded){let topic=decodeURIComponent(encoded);currentView='topics';let arr=QUESTIONS.filter(q=>q.motherTopic===topic);app.innerHTML=`<section class="hero compact"><div><p class="eyebrow">母题学习</p><h1>🟣 ${esc(topic)}</h1><p>${arr.length} 道相关题目。先学通用句，再看半通用句，最后朗读每一道完整范文。</p></div></section><section class="section"><div class="answer-panel green"><h2>🟢 这个母题的通用句</h2>${universal.slice(0,8).map(x=>`<div class="sentence"><b>${x[1]}</b><p>${esc(x[2])}</p><small>${esc(x[3])}</small></div>`).join('')}</div><div class="answer-panel teal"><h2>🔵 这个母题的半通用句</h2>${(CATEGORY_SEMI[arr[0]?.category]||[]).map(x=>`<div class="sentence"><p>${esc(x)}</p></div>`).join('')}</div></section><section class="section"><div class="section-head"><h2>本母题全部真题</h2></div><div class="grid">${arr.map(card).join('')}</div></section>`;nav()}
function topics(){currentView='topics';app.innerHTML=`<section class="hero compact"><div><p class="eyebrow">17 个核心母题</p><h1>🧩 按题型学习</h1><p>你不需要为每道题重新准备答案。先掌握母题，再用同一套语言迁移到不同题目。</p></div></section><div class="grid">${MOTHER_TOPICS.map(topicCard).join('')}</div>`;nav()}
function openQuestion(id){selected=QUESTIONS.find(q=>q.id===id);if(!selected)return;let uni=selected.universal||universal.slice(0,8),semiU=selected.semiUniversal||[];document.getElementById('modalBody').innerHTML=`<div class="question-detail"><div><span class="badge task">Tâche ${selected.task}</span><span class="badge purple">🟣 ${esc(selected.motherTopic)}</span>${selected.hot>=5?'<span class="badge hot">🔥 高频</span>':''}</div><h2>${esc(selected.question)}</h2><p class="cn large">${esc(selected.cn)}</p><div class="answer-panel purple"><h3>🟣 题型定位</h3><p><b>${esc(selected.motherTopic)}</b></p><p>这是 ${selected.task===2?'“信息询问 / 角色互动”':'“观点表达 / 论证”'} 型题目。先按下面框架组织，再进入范文。</p><ol>${selected.framework.map(x=>`<li>${esc(x)}</li>`).join('')}</ol></div><div class="answer-panel green"><h3>🟢 通用句（直接背）</h3>${uni.map(x=>`<div class="sentence"><b>${x[1]}</b><p>${esc(x[2])}</p><small>${esc(x[3])}</small></div>`).join('')}</div><div class="answer-panel teal"><h3>🔵 半通用句（按本题替换关键词）</h3>${semiU.map(x=>`<div class="sentence"><p>${esc(x)}</p></div>`).join('')}</div><div class="answer-panel green model"><h3>🟢 完整范文</h3><div class="fr-block">${esc(selected.modelAnswer).replace(/\n/g,'<br>')}</div><p class="tip">学习顺序：先听/朗读 → 看结构 → 关掉页面复述 → 最后再回看范文。</p></div><div class="actions"><button class="primary" onclick="startTimer(${selected.task===2?210:270})">▶ ${selected.task===2?'3分30秒':'4分30秒'}计时</button><button onclick="stopTimer()">⏸ 停止</button><button onclick="markDone()">✅ 已练习</button><button onclick="markMistake()">❌ 加入错题</button></div><div class="timer" id="timer">${selected.task===2?'03:30':'04:30'}</div><p class="source">题目来源：${esc(selected.source)}。公开题库属于考生回忆/整理，不是官方公开原卷；本站范文为学习用途的原创参考答案。</p></div>`;document.getElementById('modal').classList.remove('hidden')}
function phrases(){currentView='phrases';app.innerHTML=`<section class="hero compact"><div><p class="eyebrow">PRIORITÉ 1 · 先背前8句</p><h1>⭐ 14句核心万能句</h1><p>不再使用“À mon avis, ...”这种半截句。这里每一句都是可以直接说出口的完整句子。</p></div></section><div class="phrase-list">${PHRASES.map(x=>`<div class="sentence green"><div class="phrase-no">${x[0]}</div><div><b>${x[1]}</b><p>${esc(x[2])}</p><small>${esc(x[3])}</small></div></div>`).join('')}</div>`;nav()}
function framework(){currentView='framework';app.innerHTML=`<section class="hero compact"><div><p class="eyebrow">STRUCTURE</p><h1>📐 TCF 口语回答框架</h1><p>目标不是把范文全部背下来，而是让你看到题目后自动进入结构。</p></div></section><section class="framework-grid"><div class="answer-panel purple"><h2>🟣 Tâche 2 · 互动提问</h2><ol><li><b>开场</b>：Bonjour + 说明目的 + 礼貌请求。</li><li><b>基本信息</b>：时间、地点、人物、对象。</li><li><b>核心信息</b>：价格、内容、条件、可用性。</li><li><b>细节</b>：频率、设备、规则、交通、注意事项。</li><li><b>个人需求</b>：是否适合自己/孩子/家人。</li><li><b>确认</b>：报名、预订、下一步。</li><li><b>结束</b>：Merci beaucoup + 总结信息很有帮助。</li></ol></div><div class="answer-panel purple"><h2>🟣 Tâche 3 · 4分30秒</h2><ol><li><b>Introduction</b>：改写题目，不直接重复。</li><li><b>Position</b>：À mon avis, je pense que…</li><li><b>Argument 1</b>：理由 + 解释 + 例子。</li><li><b>Argument 2</b>：另一个理由或反面考虑。</li><li><b>Nuance</b>：承认另一观点有合理之处。</li><li><b>Solution</b>：提出平衡、现实的做法。</li><li><b>Conclusion</b>：重新表达立场 + 总结。</li></ol></div></section><section class="answer-panel green"><h2>🟢 Tâche 3 一套可以反复迁移的骨架</h2><div class="fr-block">De nos jours, la question de … est assez présente dans notre société.<br><br>Pour ma part, je pense qu’il faut regarder la situation dans son ensemble.<br><br>Tout d’abord, … . Par exemple, … .<br><br>Ensuite, … . Cependant, il ne faut pas oublier que … .<br><br>C’est pourquoi je pense qu’une solution équilibrée consiste à … .<br><br>En conclusion, je dirais que … . L’essentiel est de trouver une solution réaliste et adaptée à la situation.</div></section>`;nav()}
function randomQuestion(task){let arr=QUESTIONS.filter(q=>!task||q.task===task);openQuestion(arr[Math.floor(Math.random()*arr.length)].id)}
function markDone(){if(!selected)return;if(!state.done.includes(selected.id))state.done.push(selected.id);save();alert('已记录：这道题练习完成。')}
function markMistake(){if(!selected)return;if(!state.mistakes.includes(selected.id))state.mistakes.push(selected.id);save();alert('已加入错题本。')}
function mistakes(){currentView='mistakes';let arr=QUESTIONS.filter(q=>state.mistakes.includes(q.id));app.innerHTML=`<section class="hero compact"><div><p class="eyebrow">REVIEW</p><h1>❌ 错题本</h1><p>只保留你真正需要反复练习的题。</p></div></section>${arr.length?`<div class="grid">${arr.map(card).join('')}</div>`:'<div class="empty">还没有错题。</div>'}`;nav()}
function startTimer(n){stopTimer();seconds=n;const el=document.getElementById('timer');const tick=()=>{el.textContent=String(Math.floor(seconds/60)).padStart(2,'0')+':'+String(seconds%60).padStart(2,'0');el.classList.toggle('warning',seconds<=30);if(seconds<=0){stopTimer();el.textContent='时间到！';return}seconds--};tick();timer=setInterval(tick,1000)}function stopTimer(){if(timer){clearInterval(timer);timer=null}}
function route(v){currentView=v;if(v==='dashboard')dashboard();else if(v==='task2')showList(2);else if(v==='task3')showList(3);else if(v==='topics')topics();else if(v==='phrases')phrases();else if(v==='framework')framework();else if(v==='mistakes')mistakes()}
document.querySelectorAll('.nav').forEach(b=>b.addEventListener('click',()=>route(b.dataset.view)));document.getElementById('closeModal').onclick=()=>{stopTimer();document.getElementById('modal').classList.add('hidden')};document.getElementById('modal').addEventListener('click',e=>{if(e.target.id==='modal'){stopTimer();e.currentTarget.classList.add('hidden')}});dashboard();
