const app=document.getElementById('app');let currentView='dashboard',selected=null,timer=null,seconds=0;
const state={done:JSON.parse(localStorage.getItem('tcfDone')||'[]'),mistakes:JSON.parse(localStorage.getItem('tcfMistakes')||'[]')};
function save(){localStorage.setItem('tcfDone',JSON.stringify(state.done));localStorage.setItem('tcfMistakes',JSON.stringify(state.mistakes));}
function nav(){document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',b.dataset.view===currentView));}
function esc(s){return String(s??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')}
function badge(q){return `<span class="badge task">Tâche ${q.task}</span><span class="badge purple">🟣 ${esc(q.motherTopic)}</span>${q.hot>=5?'<span class="badge hot">🔥 高频</span>':''}`}
function card(q){return `<article class="card question-card" onclick="openQuestion('${q.id}')"><div>${badge(q)}</div><h3>${esc(q.question)}</h3><p class="cn">${esc(q.cn)}</p><div class="meta"><span>${q.month}</span><span>出现 ${q.appearances.length} 次</span><span>${q.task===2?'互动':'观点'}</span></div></article>`}
function dashboard(){let t2=QUESTIONS.filter(q=>q.task===2),t3=QUESTIONS.filter(q=>q.task===3);app.innerHTML=`<section class="hero"><div><p class="eyebrow">TCF QUÉBEC · EXPRESSION ORALE</p><h1>按 <em>母题 + 万能句 + 范文</em> 学口语</h1><p>每一道题都有完整范文；每个母题都有一套“差不多万能”的范文版本。绿色背万能句，蓝色学半通用句，橙色只看本题必须变化的内容。</p></div><div class="hero-actions"><button class="primary" onclick="route('task3')">开始 Tâche 3</button><button onclick="route('task2')">练 Tâche 2</button></div></section><section class="stats"><div><small>Tâche 2</small><b>${t2.length}</b><span>互动题</span></div><div><small>Tâche 3</small><b>${t3.length}</b><span>观点题</span></div><div><small>母题</small><b>${MOTHER_TOPICS.length}</b><span>主题归类</span></div><div><small>万能句</small><b>${UNIVERSAL.length}</b><span>持续扩充</span></div></section><section class="section"><div class="legend"><div class="legend-item purple-bg"><b>🟣 题型 / 母题</b><span>回答结构和题目属于哪一类。</span></div><div class="legend-item green-bg"><b>🟢 万能句</b><span>跨多个主题都可以直接使用，值得背熟。</span></div><div class="legend-item teal-bg"><b>🔵 半通用句</b><span>句型基本固定，只需要根据题目换几个词。</span></div><div class="legend-item orange-bg"><b>🟠 本题具体内容</b><span>范文中必须随题目变化的词句，不需要你填写。</span></div></div></section><section class="section"><div class="section-head"><h2>🔥 高频母题</h2><button onclick="route('topics')">查看全部</button></div><div class="grid">${MOTHER_TOPICS.slice(0,6).map(topicCard).join('')}</div></section><section class="section"><div class="section-head"><h2>近期高频题</h2></div><div class="grid">${QUESTIONS.filter(q=>q.hot>=5).slice(0,6).map(card).join('')}</div></section>`;nav()}
function topicCard(topic){let arr=QUESTIONS.filter(q=>q.motherTopic===topic);return `<article class="card topic-card" onclick="openTopic('${encodeURIComponent(topic)}')"><span class="badge purple">🟣 母题</span><h3>${esc(topic)}</h3><p>${arr.length} 道题 · Tâche 2 ${arr.filter(x=>x.task===2).length} · Tâche 3 ${arr.filter(x=>x.task===3).length}</p><div class="mini">${arr.filter(x=>x.hot>=5).length} 道高频</div></article>`}
function showList(task){currentView=task===2?'task2':'task3';let arr=QUESTIONS.filter(q=>q.task===task);app.innerHTML=`<section class="hero compact"><div><p class="eyebrow">${task===2?'INTERACTION':'POINT DE VUE'}</p><h1>Tâche ${task}</h1><p>${task===2?'重点：学会自然、连续、有层次地提问。':'重点：掌握可迁移到不同话题的 4 分 30 秒论证结构。'} 每道题都有完整范文和颜色标注。</p></div><button class="primary" onclick="randomQuestion(${task})">🎲 随机一题</button></section><section class="filters"><select id="topic"><option value="">全部母题</option>${[...new Set(arr.map(q=>q.motherTopic))].map(x=>`<option>${esc(x)}</option>`).join('')}</select><select id="month"><option value="">全部月份</option>${[...new Set(arr.map(q=>q.month))].sort().reverse().map(x=>`<option>${x}</option>`).join('')}</select><select id="hot"><option value="">全部频率</option><option value="5">🔥 高频</option><option value="4">高频以上</option></select><input id="search" placeholder="搜索题目、主题或中文…"></section><div id="list" class="grid"></div>`;['topic','month','hot','search'].forEach(id=>document.getElementById(id).addEventListener('input',renderList));renderList();nav()}
function renderList(){let task=currentView==='task2'?2:3,topic=document.getElementById('topic').value,month=document.getElementById('month').value,hot=document.getElementById('hot').value,s=document.getElementById('search').value.toLowerCase();let arr=QUESTIONS.filter(q=>q.task===task&&(!topic||q.motherTopic===topic)&&(!month||q.month===month)&&(!hot||q.hot>=+hot)&&(!s||(q.question+q.cn+q.motherTopic).toLowerCase().includes(s)));document.getElementById('list').innerHTML=arr.length?arr.map(card).join(''):'<div class="empty">没有符合条件的题目。</div>'}
function universalBlock(limit=UNIVERSAL.length){return `<div class="answer-panel green"><h3>🟢 万能句：直接背</h3>${UNIVERSAL.slice(0,limit).map(x=>`<div class="sentence"><b>${esc(x[4])} · ${esc(x[1])}</b><p>${esc(x[2])}</p><small>${esc(x[3])}</small></div>`).join('')}</div>`}
function semiBlock(q){let arr=q?.semiUniversal||[];return `<div class="answer-panel teal"><h3>🔵 半通用句：根据题目微调</h3>${arr.length?arr.map(x=>`<div class="sentence"><p>${esc(x)}</p></div>`).join(''):'<p>本题使用母题范文中的半通用结构，根据具体题目替换关键词即可。</p>'}</div>`}
function topicTemplate(topic,task){let t=TOPIC_TEMPLATES[topic]?.[String(task)];if(!t)return '';return `<div class="template-card"><div class="template-title">${task===2?'Tâche 2':'Tâche 3'} · ${esc(t[0])}</div><div class="template-body"><div class="model-line green-line">${esc(t[1])}</div><div class="model-line teal-line">${esc(t[2])}</div><div class="model-line orange-line">${esc(t[3])}</div><div class="model-line green-line">${esc(t[4])}</div></div><div class="mini">🟢 可以跨题保留　🔵 换少量关键词　🟠 本主题具体内容</div></div>`}
function openTopic(encoded){let topic=decodeURIComponent(encoded);currentView='topics';let arr=QUESTIONS.filter(q=>q.motherTopic===topic);app.innerHTML=`<section class="hero compact"><div><p class="eyebrow">母题学习</p><h1>🟣 ${esc(topic)}</h1><p>${arr.length} 道题。先学母题通用范文，再看每一道真题的微调版。</p></div></section><section class="section"><div class="section-head"><h2>🟣 母题通用范文</h2><span class="mini">不是死背全文，而是背绿色 + 蓝色结构</span></div>${topicTemplate(topic,arr.some(x=>x.task===3)?3:2)}${arr.some(x=>x.task===2)?topicTemplate(topic,2):''}${arr.some(x=>x.task===3)?topicTemplate(topic,3):''}</section>${universalBlock(12)}<section class="section"><div class="section-head"><h2>本母题全部真题</h2></div><div class="grid">${arr.map(card).join('')}</div></section>`;nav()}
function topics(){currentView='topics';app.innerHTML=`<section class="hero compact"><div><p class="eyebrow">${MOTHER_TOPICS.length} 个核心母题</p><h1>🧩 按题型归类学习</h1><p>每个母题都有：🟢万能句 → 🔵半通用句 → 🟣母题通用范文 → 每道真题的完整微调范文。</p></div></section><div class="grid">${MOTHER_TOPICS.map(topicCard).join('')}</div>`;nav()}
function sentenceClass(s,task,i,total){let lower=s.toLowerCase();if(task===2){if(i===0||i===total-1||/bonjour|merci|je voudrais|j’aimerais|pourriez-vous me/i.test(s)) return 'green-line';return 'teal-line'}if(/à mon avis|pour ma part|tout d’abord|ensuite|cependant|en conclusion|en définitive|c’est pourquoi|au final|pour toutes ces raisons|d’un côté|de l’autre|par exemple|en effet/i.test(s)) return 'green-line';if(/mon expérience|prenons un exemple|par exemple|dans la vie|les enfants|les parents|le travail|les réseaux|le logement|les transports|les voyages|la technologie|l’environnement|la santé/i.test(lower)) return 'orange-line';return 'teal-line'}
function coloredModel(answer,task){let parts=String(answer||'').split(/\n+/).map(x=>x.trim()).filter(Boolean);return `<div class="model-highlight">${parts.map((s,i)=>`<div class="model-line ${sentenceClass(s,task,i,parts.length)}"><span class="model-tag">${sentenceClass(s,task,i,parts.length)==='green-line'?'🟢 万能':sentenceClass(s,task,i,parts.length)==='teal-line'?'🔵 半通用':'🟠 本题内容'}</span>${esc(s)}</div>`).join('')}</div>`}
function openQuestion(id){selected=QUESTIONS.find(q=>q.id===id);if(!selected)return;document.getElementById('modalBody').innerHTML=`<div class="question-detail"><div>${badge(selected)}</div><h2>${esc(selected.question)}</h2><p class="cn large">${esc(selected.cn)}</p><div class="answer-panel purple"><h3>🟣 题型 / 回答框架</h3><p><b>${esc(selected.motherTopic)}</b></p><ol>${selected.framework.map(x=>`<li>${esc(x)}</li>`).join('')}</ol></div>${universalBlock(selected.task===2?10:16)}${semiBlock(selected)}<div class="answer-panel green model"><h3>🟢🔵🟠 完整范文（已经按颜色拆开）</h3><div class="color-key"><span>🟢 万能：尽量背熟</span><span>🔵 半通用：看到题目稍微改</span><span>🟠 本题内容：随题变化</span></div>${coloredModel(selected.modelAnswer,selected.task)}<p class="tip">学习顺序：①先看🟣结构 → ②背🟢 → ③熟悉🔵 → ④理解🟠内容 → ⑤关掉页面复述。</p></div><div class="actions"><button class="primary" onclick="startTimer(${selected.task===2?210:270})">▶ ${selected.task===2?'3分30秒':'4分30秒'}计时</button><button onclick="stopTimer()">⏸ 停止</button><button onclick="markDone()">✅ 已练习</button><button onclick="markMistake()">❌ 加入错题</button></div><div class="timer" id="timer">${selected.task===2?'03:30':'04:30'}</div><p class="source">题目来源：${esc(selected.source)}。公开题库属于考生回忆/整理，不是官方公开原卷；本站范文为学习用途的原创参考答案。</p></div>`;document.getElementById('modal').classList.remove('hidden')}
function phrases(){currentView='phrases';let groups={};UNIVERSAL.forEach(x=>(groups[x[4]]??=[]).push(x));app.innerHTML=`<section class="hero compact"><div><p class="eyebrow">可持续扩充 · 不限14句</p><h1>⭐ 万能句库 · ${UNIVERSAL.length}句</h1><p>这里不再限定“14句”。只要一句话可以跨多个母题稳定复用，就继续收进来。前14句作为核心基础，其余作为扩展。</p></div></section>${Object.entries(groups).map(([g,arr])=>`<section class="section"><h2>${esc(g)}</h2><div class="phrase-list">${arr.map(x=>`<div class="sentence green"><div class="phrase-no">${x[0]}</div><div><b>${esc(x[1])}</b><p>${esc(x[2])}</p><small>${esc(x[3])}</small></div></div>`).join('')}</div></section>`).join('')}`;nav()}
function framework(){currentView='framework';app.innerHTML=`<section class="hero compact"><div><p class="eyebrow">STRUCTURE</p><h1>📐 TCF 口语回答框架</h1><p>把“背答案”变成“背结构”。遇到新题时，先识别母题，再套结构。</p></div></section><section class="framework-grid"><div class="answer-panel purple"><h2>🟣 Tâche 2 · 互动提问</h2><ol><li><b>开场</b>：说明目的 + 礼貌请求。</li><li><b>基本信息</b>：时间、地点、人物、对象。</li><li><b>核心信息</b>：价格、内容、条件、可用性。</li><li><b>细节追问</b>：频率、设备、规则、交通、注意事项。</li><li><b>个人需求</b>：是否适合自己/孩子/家人。</li><li><b>确认</b>：报名、预订、下一步。</li><li><b>结束</b>：感谢 + 重申信息很有帮助。</li></ol></div><div class="answer-panel purple"><h2>🟣 Tâche 3 · 4分30秒</h2><ol><li><b>Introduction</b>：改写题目 + 引出问题。</li><li><b>Position</b>：明确但不极端的立场。</li><li><b>Argument 1</b>：理由 + 解释 + 例子。</li><li><b>Argument 2</b>：第二理由 + 结果/例子。</li><li><b>Nuance</b>：承认另一面。</li><li><b>Solution</b>：提出平衡、现实的做法。</li><li><b>Conclusion</b>：总结并重申立场。</li></ol></div></section><section class="section"><h2>🟢 可直接背的 Tâche 3 骨架</h2><div class="answer-panel green"><div class="model-highlight"><div class="model-line green-line">De nos jours, la question de … occupe une place importante dans notre société.</div><div class="model-line green-line">Pour ma part, je pense qu’il faut regarder la situation dans son ensemble.</div><div class="model-line teal-line">Tout d’abord, le principal avantage est que … . Par exemple, … .</div><div class="model-line teal-line">Ensuite, il faut également prendre en compte le fait que … .</div><div class="model-line orange-line">Prenons un exemple concret lié au sujet : … .</div><div class="model-line teal-line">Cependant, il ne faut pas oublier que cette solution présente aussi certaines limites.</div><div class="model-line green-line">C’est pourquoi je privilégierais une solution équilibrée qui permette de conserver les avantages tout en réduisant les risques.</div><div class="model-line green-line">En conclusion, je pense qu’il faut surtout rechercher une solution réaliste et adaptée au contexte.</div></div></div></section>`;nav()}
function randomQuestion(task){let arr=QUESTIONS.filter(q=>!task||q.task===task);openQuestion(arr[Math.floor(Math.random()*arr.length)].id)}
function markDone(){if(!selected)return;if(!state.done.includes(selected.id))state.done.push(selected.id);save();alert('已记录：这道题练习完成。')}
function markMistake(){if(!selected)return;if(!state.mistakes.includes(selected.id))state.mistakes.push(selected.id);save();alert('已加入错题本。')}
function mistakes(){currentView='mistakes';let arr=QUESTIONS.filter(q=>state.mistakes.includes(q.id));app.innerHTML=`<section class="hero compact"><div><p class="eyebrow">REVIEW</p><h1>❌ 错题本</h1><p>只保留你真正需要反复练习的题。</p></div></section>${arr.length?`<div class="grid">${arr.map(card).join('')}</div>`:'<div class="empty">还没有错题。</div>'}`;nav()}
function startTimer(n){stopTimer();seconds=n;const el=document.getElementById('timer');const tick=()=>{el.textContent=String(Math.floor(seconds/60)).padStart(2,'0')+':'+String(seconds%60).padStart(2,'0');el.classList.toggle('warning',seconds<=30);if(seconds<=0){stopTimer();el.textContent='时间到！';return}seconds--};tick();timer=setInterval(tick,1000)}function stopTimer(){if(timer){clearInterval(timer);timer=null}}
function route(v){currentView=v;if(v==='dashboard')dashboard();else if(v==='task2')showList(2);else if(v==='task3')showList(3);else if(v==='topics')topics();else if(v==='phrases')phrases();else if(v==='framework')framework();else if(v==='mistakes')mistakes()}
document.querySelectorAll('.nav').forEach(b=>b.addEventListener('click',()=>route(b.dataset.view)));document.getElementById('closeModal').onclick=()=>{stopTimer();document.getElementById('modal').classList.add('hidden')};document.getElementById('modal').addEventListener('click',e=>{if(e.target.id==='modal'){stopTimer();e.currentTarget.classList.add('hidden')}});dashboard();
