const app=document.getElementById('app');let currentView='dashboard';let timer=null;let seconds=0;let selected=null;
const state={done:JSON.parse(localStorage.getItem('tcfDone')||'[]'),mistakes:JSON.parse(localStorage.getItem('tcfMistakes')||'[]'),notes:JSON.parse(localStorage.getItem('tcfNotes')||'{}')};
function save(){localStorage.setItem('tcfDone',JSON.stringify(state.done));localStorage.setItem('tcfMistakes',JSON.stringify(state.mistakes));localStorage.setItem('tcfNotes',JSON.stringify(state.notes));}
function nav(){document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',b.dataset.view===currentView));}
function dashboard(){let t2=QUESTIONS.filter(q=>q.task===2).length,t3=QUESTIONS.filter(q=>q.task===3).length;app.innerHTML=`<div class="hero"><div><h2>Bienvenue dans TCF Québec Oral Lab 👋</h2><p>把历年公开题目回忆变成“母题 + 万能答案 + 自己输出”的训练系统。</p><p class="small">当前题库：${QUESTIONS.filter(q=>q.task===2).length} 道 Tâche 2 · ${QUESTIONS.filter(q=>q.task===3).length} 道 Tâche 3</p></div><button class="primary" onclick="route('task2')">🔥 Tâche 2 高频</button><button onclick="route('task3')">🗣️ Tâche 3 高频</button></div><div class="stats"><div class="stat">Tâche 2<b>${t2}</b><span class="small">互动题</span></div><div class="stat">Tâche 3<b>${t3}</b><span class="small">观点题</span></div><div class="stat">已完成<b>${state.done.length}</b><span class="small">本机保存</span></div><div class="stat">错题<b>${state.mistakes.length}</b><span class="small">需要复习</span></div></div><div class="section"><div class="section-head"><h3>三色学习法</h3></div><div class="grid"><div class="card block type"><div class="block-title">🟣 题型 / 题目</div><b>先看母题结构</b><p>先判断主题，再确定你要问什么或论证什么。</p></div><div class="card block answer"><div class="block-title">🟢 通用答案</div><b>先背结构，不背整篇</b><p>用连接词、论证框架和高频表达快速组织语言。</p></div><div class="card block fill"><div class="block-title">🟠 自填内容</div><b>把答案变成你的</b><p>替换例子、个人经历、城市、职业和观点。</p></div><div class="card practice"><b>🎙️ 目标</b><p>最后必须脱离答案自己说出来。网站会保存你的练习笔记。</p></div></div></div><div class="section"><div class="section-head"><h3>🔥 当前高频母题</h3><button onclick="showList(5)">查看全部</button></div><div class="grid">${QUESTIONS.filter(q=>q.hot>=5).slice(0,4).map(card).join('')}</div></div>`;nav();}
function card(q){return `<div class="card question-card" onclick="openQuestion('${q.id}')"><span class="badge task">Tâche ${q.task}</span><span class="badge type">${q.category}</span>${q.hot>=5?'<span class="badge hot">🔥 高频</span>':''}<h4>${q.question}</h4><div class="cn">${q.cn}</div><div class="meta"><span>${q.month}</span><span>${q.source}</span><span>出现 ${q.appearances.length} 次</span></div></div>`}
function showList(hot=0){app.innerHTML=`<div class="hero"><div><h2>${currentView==='task2'?'Tâche 2 · Interaction':'Tâche 3 · Point de vue'}</h2><p>按主题、月份和频率筛选。点击题目进入练习。</p></div></div><div class="filters"><select id="cat"><option value="">全部主题</option>${[...new Set(QUESTIONS.filter(q=>q.task===(currentView==='task2'?2:3)).map(q=>q.category))].map(x=>`<option>${x}</option>`).join('')}</select><select id="month"><option value="">全部月份</option>${[...new Set(QUESTIONS.map(q=>q.month))].sort().reverse().map(x=>`<option>${x}</option>`).join('')}</select><select id="hot"><option value="">全部频率</option><option value="5">🔥 高频</option><option value="4">高频</option></select><input class="search" id="search" placeholder="搜索关键词…"></div><div id="list" class="grid" style="margin-top:14px"></div>`;['cat','month','hot','search'].forEach(id=>document.getElementById(id).addEventListener('input',renderList));renderList();nav();}
function renderList(){let task=currentView==='task2'?2:3;let cat=document.getElementById('cat').value,month=document.getElementById('month').value,hot=document.getElementById('hot').value,s=document.getElementById('search').value.toLowerCase();let arr=QUESTIONS.filter(q=>q.task===task&&(!cat||q.category===cat)&&(!month||q.month===month)&&(!hot||q.hot>=+hot)&&(!s||(q.question+q.cn+q.category).toLowerCase().includes(s)));document.getElementById('list').innerHTML=arr.length?arr.map(card).join(''):'<div class="empty">没有找到符合条件的题目。</div>';}
function openQuestion(id){selected=QUESTIONS.find(q=>q.id===id);if(!selected)return;const note=state.notes[id]||'';document.getElementById('modalBody').innerHTML=`<div class="practice"><span class="badge task">Tâche ${selected.task}</span><span class="category">${selected.category}</span><h2>${selected.question}</h2><p class="cn">${selected.cn}</p><div class="block type"><div class="block-title">🟣 题型 / 母题结构</div><ul>${(selected.template||['观点','理由1','例子','理由2','总结']).map(x=>`<li>${x}</li>`).join('')}</ul></div><div class="block answer"><div class="block-title">🟢 通用参考答案</div><p class="fr">${selected.answer}</p><p class="small">建议：先理解结构，再用自己的词重新说，不要机械背全文。</p></div><div class="block fill"><div class="block-title">🟠 自填内容 / 我的版本</div><textarea id="note" placeholder="把个人经历、例子、城市、职业等换成你自己的内容……">${note}</textarea></div><div class="timer" id="timer">${selected.task===2?'03:30':'03:00'}</div><div class="actions"><button class="primary" onclick="startTimer(${selected.task===2?210:180})">▶ 开始计时</button><button onclick="stopTimer()">⏸ 停止</button><button onclick="markDone()">✅ 我练完了</button><button onclick="markMistake()">❌ 加入错题</button></div><div class="source">资料来源：${selected.source}。本网站答案为学习用途的原创参考答案，并非官方评分答案；公开题库通常属于考生回忆/整理。</div></div>`;document.getElementById('modal').classList.remove('hidden');}
function startTimer(n){stopTimer();seconds=n;const el=document.getElementById('timer');const tick=()=>{let m=String(Math.floor(seconds/60)).padStart(2,'0'),s=String(seconds%60).padStart(2,'0');el.textContent=`${m}:${s}`;el.classList.toggle('warning',seconds<=30);if(seconds<=0){stopTimer();el.textContent='时间到！';return}seconds--};tick();timer=setInterval(tick,1000)}function stopTimer(){if(timer){clearInterval(timer);timer=null}}
function markDone(){if(!selected)return;state.notes[selected.id]=document.getElementById('note')?.value||'';if(!state.done.includes(selected.id))state.done.push(selected.id);save();alert('已保存为完成练习。');}
function markMistake(){if(!selected)return;state.notes[selected.id]=document.getElementById('note')?.value||'';if(!state.mistakes.includes(selected.id))state.mistakes.push(selected.id);save();alert('已加入错题本。');}
function randomQuestion(){const q=QUESTIONS[Math.floor(Math.random()*QUESTIONS.length)];openQuestion(q.id)}
function exam(){const pool=[...QUESTIONS].sort(()=>Math.random()-.5).slice(0,3);currentView='dashboard';document.getElementById('modalBody').innerHTML=`<div class="practice"><h2>⏱ 模拟考试</h2><p class="cn">随机抽取 3 题：Tâche 2 + Tâche 3。每题开始前不要看参考答案。</p>${pool.map((q,i)=>`<div class="block type"><b>${i+1}. Tâche ${q.task} · ${q.category}</b><p class="fr">${q.question}</p></div>`).join('')}<div class="timer" id="timer">09:30</div><div class="actions"><button class="primary" onclick="startTimer(570)">▶ 开始整套计时</button><button onclick="stopTimer()">⏸ 停止</button></div></div>`;document.getElementById('modal').classList.remove('hidden');}
function phrases(){app.innerHTML=`<div class="hero"><div><h2>⭐ 14句核心万能句</h2><p>绿色统一表示“通用答案/万能表达”。橙色输入框用来替换成你的内容。</p></div></div><div class="phrase-list">${PHRASES.map(p=>`<div class="phrase"><div class="num">${p.id}</div><div><b>${p.fr}</b><div class="cn">${p.cn}</div></div><input class="fill-input" placeholder="我的例子 / 关键词" value="${localStorage.getItem('phrase_'+p.id)||''}" onchange="localStorage.setItem('phrase_${p.id}',this.value)"></div>`).join('')}</div>`;nav()}
function mistakes(){let arr=QUESTIONS.filter(q=>state.mistakes.includes(q.id));app.innerHTML=`<div class="hero"><div><h2>❌ 我的错题</h2><p>反复练习你真正卡住的题。</p></div></div>${arr.length?`<div class="grid">${arr.map(card).join('')}</div>`:'<div class="card empty">还没有错题。练习时点击“加入错题”即可。</div>'}`;nav()}
function route(v){currentView=v;if(v==='dashboard')dashboard();else if(v==='task2'||v==='task3')showList();else if(v==='phrases')phrases();else mistakes()}
document.querySelectorAll('.nav').forEach(b=>b.addEventListener('click',()=>route(b.dataset.view)));document.getElementById('randomBtn').onclick=randomQuestion;document.getElementById('examBtn').onclick=exam;document.getElementById('closeModal').onclick=()=>{stopTimer();document.getElementById('modal').classList.add('hidden')};document.getElementById('modal').addEventListener('click',e=>{if(e.target.id==='modal'){stopTimer();e.currentTarget.classList.add('hidden')}});dashboard();
